server:
  port: 8923
  tomcat:
    uri-encoding: utf-8
    max-connections: 30000

spring:
  profiles:
    active: dev

  thymeleaf:
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  aop:
    proxy-target-class: true
